version: "3.8"

services:
  client:
    build:
      context: ./client/insightecr
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    volumes:
      - ./client/insightecr:/app
      - /app/node_modules
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - fennecr-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - dynamodb
    env_file:
      - .env
    networks:
      - fennecr-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodbdata:/data
    env_file:
      - .env
    networks:
      - fennecr-network

volumes:
  dynamodbdata:

networks:
  fennecr-network:
    driver: bridge
