version: '3.8'

services:
  client:
    image: petergaoxl/insightecr-client
    ports:
      - "80:80"
    depends_on:
      - server
    env_file:
      - .env
    networks:
      - insightecr-network

  server:
    image: petergaoxl/insightecr-server
    ports:
      - "3000:3000"
    container_name: insightecr-server-1
    depends_on:
      - dynamodb
    env_file:
      - .env
    networks:
      - insightecr-network

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodbdata:/data
    env_file:
      - .env
    networks:
      - insightecr-network

volumes:
  dynamodbdata:

networks:
  insightecr-network:
    driver: bridge
