FROM node:20 as build

# workdir
WORKDIR /app

# copy package.json
COPY package.json ./
# COPY package-lock.json ./

# install dependency
RUN npm install --verbose

# Copy everything
COPY . ./

# 
RUN npm run build

# Production
FROM nginx:latest

# 
COPY --from=build /app/dist /usr/share/nginx/html

# Nginx conf
COPY nginx.conf /etc/nginx/nginx.conf

# expose Nginx port
EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]
