# Base image
FROM node:20

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json if available
COPY package.json ./

# Install dependencies
RUN npm install

# Install TypeScript and ts-node globally
RUN npm install -g typescript ts-node

# Copy the rest of the application code
COPY . .

# Compile TypeScript files
RUN npx tsc

# Expose port
EXPOSE 3000

# Start the application
# CMD ["ts-node", "src/index.ts"]
CMD ["node", "dist/index.js"]
